apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-of-PROJECT
  labels:
    app: mysql-of-PROJECT
spec:
  replicas: REPLICAS
  selector:
    matchLabels:
      app: mysql-of-PROJECT
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-of-PROJECT
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: MysqlRootPassword
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-of-PROJECT-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql-of-PROJECT
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None # 这是一个Headless Service，适用于有状态应用
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-of-PROJECT-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
